### ISSUE TITLE
Add readme file for home page

### ISSUE THREAD

**Issue by ay2306** [ay2306/graphviz-cp-simplifier#11]
Things required in the readme file
1. What is the project?
2. How you can run the project?
3. How you can use the project? - APIs and Browser Stuff

**Comment by anshika2306** [comment]
can I take this up?

**Comment by Premjeet1804** [comment]
how can i contribute in that

**Comment by ay2306** [comment]
I will add more issues that you can take up. I think it will be difficult to write it without context. Since @anshika2306 is the co-author of this project, I think I will assign this one to her.

**Comment by ay2306** [comment]
Fixed in PR #17
